name: int222-frontend-prd
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo VUE_APP_BACKEND_URL=${{ secrets.PRD_BACKEND_URL }} >> .env

      - name: Login to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/int222/frontend:prd

      - name: Publish compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./docker-compose-prd.yml
          target: ~/frontend/prd/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-compose -f ~/frontend/prd/docker-compose-prd.yml pull
            docker-compose -f ~/frontend/prd/docker-compose-prd.yml up -d
